---
version: '2'
services:
  odoo:
    container_name: ${NAME}
    image: ${REPO}:${ODVER}
    depends_on:
      - database
      - addons
    environment:
      - NAME=${NAME}
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - ADDONDIR=${ADDONDIR}
    networks:
      - network
    ports:
      - ${PORT}:8069
    volumes:
      - run_data:/var/run/postgresql
      - addons_data:/mnt/extra-addons

  database:                
    container_name: ${HOST}
    image: ${DBREPO}:${DBVER}
    networks:
      - network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
 #     - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - run_data:/var/run/postgresql
      - db_data:/var/lib/postgresql/data
      
  addons:
    container_name: ${NAME}_addons
    image: ${ADREPO}:latest
    networks:
      - network
    environment:
      - ADREPO=${ADREPO}
      - URLE=${URLE}
      - URL1=${URL1}
      - URL2=${URL2}
      - URL3=${URL3}
      - BRANCHE=${ODVER}.0
      - BRANCH1=${BRANCH1}
      - BRANCH2=${BRANCH2}
      - BRANCH3=${BRANCH3}
      - ADDONDIR=${ADDONDIR}
    volumes:
      - addons_data:/mnt/extra-addons
      
networks:
  network:
  
volumes:
  run_data:
    name: ${NAME}_run_data
  addons_data:
    name: ${NAME}_addons_data
  db_data:
    name: ${NAME}_db_data
