---
version: '2'
services:
  odoo:
    container_name: ${NAME}
    image: ${REPO}:${ODVER}
    depends_on:
      - database
    environment:
      - NAME=${NAME}
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - ADDONDIR=${ADDONDIR}
    ports:
      - ${PORT}:8069
    volumes:
      - run_data:/var/run/postgresql
      - addons_data:/mnt/extra-addons

  database:                
    container_name: ${HOST}
    image: ${DBREPO}:${DBVER}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
 #     - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - run_data:/var/run/postgresql
      - db_data:/var/lib/postgresql/data
      
volumes:
  run_data:
  addons_data:
  db_data:
