---
version: '2'
services:
  odoo:
    container_name: ${NAME}
    image: ${REPO}:${ODVER}
    depends_on:
      - database
    environment:
      - NAME=${NAME}
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - ADDONDIR=${ADDONDIR}
    ports:
      - ${PORT}:8069
    volumes:
      - var:/var
      - addons:/mnt/extra-addons

  database:                
    container_name: ${HOST}
    image: ${DBREPO}:${DBVER}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - var:/var

volumes:
  var:
    driver_opts:
      type: none
      device: ${FILEPATH}${NAME}/var
      o: bind
  addons:
    driver_opts:
      type: none
      device: ${FILEPATH}${NAME}/addons
      o: bind
