---
version: '2'
services:
  odoo:
    container_name: ${NAME}
    image: smartit/odoo:13
    depends_on:
      - database
    environment:
      - NAME=${NAME}
      - HOST=${HOST}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - ADDONDIR=${ADDONDIR}
    ports:
      - ${PORT}:8069
    volumes:
      - /docker/${NAME}/var:/var
      - /docker/${NAME}/addons:/mnt/extra-addons

  database:                
    container_name: ${HOST}
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /docker/${NAME}/var:/var
