---
version: '2'
services:
  odoo:
    container_name: ${TYPE}_${NAME}
    image: ${REPO}:${ODVER}
    depends_on:
      - database
      - addons
    environment:
      - NAME=${NAME}
      - HOST=${TYPE}_${NAME}_db
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - ADDONDIR=${ADDONDIR}
    resources:
        limits:
          #cpus: '0.50'
          memory: 2048M
        reservations:
          #cpus: '0.25'
          memory: 512M
    networks:
      - network
    ports:
      - ${PORT}:8069
    volumes:
      - /mnt/smartit/share/container_data/${NAME}/odoo:/opt/odoo
#      - /mnt/smartit/share/container_data/${NAME}/postgres/run:/var/run/postgresql
      - run_data:/var/run/postgresql
#      - /mnt/smartit/share/container_data/${NAME}/addons:/mnt/extra-addons
      - addons_data:/mnt/extra-addons
      - /mnt/smartit/share/shared_data:/mnt/shared_data
      - /etc/nginx/docker/:/etc/nginx/
      - /mnt/smartit/share/container_data/${NAME}/logs:/var/log/odoo

  database:                
    container_name: ${TYPE}_${NAME}_db
    image: ${DBREPO}:${DBVER}
    networks:
      - network
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - DB_NAME=${NAME}
 #     - PGDATA=/var/lib/postgresql/data/pgdata
    resources:
        limits:
          #cpus: '0.50'
          memory: 512M
        reservations:
          #cpus: '0.25'
          memory: 256M
    volumes:
      - /mnt/smartit/share/container_data/${NAME}/odoo:/opt/odoo/
      - run_data:/var/run/postgresql
#      - /mnt/smartit/share/container_data/${NAME}/postgres/data:/var/lib/postgresql/data
      - db_data:/var/lib/postgresql/data
      - /mnt/smartit/share/shared_data:/mnt/shared_data
      
  addons:
    container_name: ${TYPE}_${NAME}_addons
    image: ${ADREPO}:${ODVER}
    networks:
      - network
    environment:
      - ADREPO=${ADREPO}
      - URL1=${URL1}
      - URL2=${URL2}
      - URL3=${URL3}
      - BRANCH1=${BRANCH1}
      - BRANCH2=${BRANCH2}
      - BRANCH3=${BRANCH3}
      - ADDONDIR=${ADDONDIR}
    resources:
        limits:
          #cpus: '0.50'
          memory: 16M
        reservations:
          #cpus: '0.25'
          memory: 8M
    volumes:
      - /mnt/smartit/share/container_data/${NAME}/odoo:/opt/odoo/
      - addons_data:/mnt/extra-addons
      - /mnt/smartit/share/shared_data:/mnt/shared_data
      
networks:
  network:

volumes:
#  conf_data:
#    name: ${NAME}_conf_data
  run_data:
    name: ${NAME}_run_data
  addons_data:
    name: ${NAME}_addons_data
  db_data:
    name: ${NAME}_db_data
